More nullable checks and fixed minor bugs
Klocman/Bulk-Crap-Uninstaller pull request #378
Opened 2022-05-25 09:33 UTC by GermanAizek

@Klocman, review pr code changes and feedback me.

2022-06-11 15:45 UTC, Klocman requested changes
Thank you for the PR!

Most of the changes are unnecessary as explained in the comments. Please either undo them or place the DisplayVersion fix in a separate PR.

2022-06-11 15:45 UTC, Klocman commented on source/BulkCrapUninstaller/Functions/AppPropertiesGatherer.cs
> +            var valueNames = targetKey?.GetValueNames();
With the check added this will throw a nullreference in the next line instead.

2022-06-11 15:45 UTC, Klocman commented on source/BulkCrapUninstaller/Functions/AppUninstaller.cs
> +                            item?.RunUninstaller(false, Settings.Default.AdvancedSimulate).WaitForExit(60000);
With the check added this will throw a nullreference in the next line instead.

2022-06-11 15:45 UTC, Klocman commented on source/BulkCrapUninstaller/Functions/Ratings/RatingRenderer.cs
> +            var aspect = (RatingEntry) (Aspect ?? false);
This will throw an invalid cast exception.

2022-06-11 15:45 UTC, Klocman commented on source/BulkCrapUninstaller/Functions/Ratings/RatingRenderer.cs
> +                else if (aspectValue <= (float) (_maximumValue + _minimumValue) / 2) numberOfImages = 2;
I believe the clamping is intentional.

2022-06-11 15:45 UTC, Klocman commented on source/KlocTools/Controls/WindowTargeter.cs
> +            label3.Text = windowHoverEventArgs.TargetWindow?.GetRunningProcess().MainModule.FileName;
This can never be null.

2022-06-11 15:45 UTC, Klocman commented on source/NBug_custom/Core/Util/Storage/ZipStorer.cs
> +                    var pos = ZipFileStream?.Position;
This can never be null.

2022-06-11 15:45 UTC, Klocman commented on source/ObjectListView/CellEditing/CellEditKeyEngine.cs
> +            if (olvi == null || (this.ItemBeingEdited == olvi && this.SubItemIndexBeingEdited == subItemIndex))
This should never be null.

2022-06-11 15:45 UTC, Klocman commented on source/ObjectListView/DragDrop/DropSink.cs
> +                if (info.Item != null)
This should never be null.

2022-06-11 15:45 UTC, Klocman commented on source/UninstallTools/Controls/UninstallListEditor.cs
> +            item.SubItems[0].Text = tag?.Name;
With the check added this will throw a nullreference below instead.

2022-06-11 15:45 UTC, Klocman commented on source/UninstallTools/Factory/DirectoryFactory.cs
> +                    return x?.GetDirectories();
This can never be null.

2022-06-11 15:45 UTC, Klocman commented on source/UninstallTools/Factory/InfoAdders/GenerateSteamHelperStrings.cs
> +            var appId = target?.RatingId.Split(new[] { " " }, StringSplitOptions.RemoveEmptyEntries).Last();
This can never be null.

2022-06-11 15:45 UTC, Klocman commented on source/UninstallTools/Factory/InfoAdders/MsiInfoAdder.cs
> +                entry.InstallDate = new DateTime(int.Parse(temp?.Substring(0, 4)),
This can never be null.

2022-08-08 20:40 UTC, Klocman commented
I added fixes to confirmed issues in separate commits, so I'll be closing the PR now. Thank you for finding these.

2022-08-08 20:40 UTC, closed without merging

2022-08-08 20:45 UTC, GermanAizek commented
@Klocman, ok. Thx for contribution!